siddhiiguptaa/100DaysofCode

.gitignore
DAY1/LargestNumberInArray/LargestNumberInArray.cs
DAY1/LargestNumberInArray/LargestNumberInArray.csproj
DAY1/LargestNumberInArray/Program.cs

Added day 1
Determine whether the largest element in the array is at least twice as much as every other number in the array. If it is, return the index of the largest element, or return -1 otherwise.

Add Largest Number in array

---

DAY1/randomhtml.html

randomhtml.html

---

DAY1/README_symmetricDifference.md
DAY1/readme.md
DAY1/symmetricDifference.js

“The best thing about a Boolean is even if you are wrong, you are only off by a bit.”

Symmetric Difference || Algorithms

---

DAY2/MaxCandy

Geek wants to make a special space for candies on his bookshelf. Currently, it has N books of different heights, represented by the array height[] and unit width.
Help him select 2 books such that he can store maximum candies between them by removing all the other books from between the selected books. The task is to find out the area between two books that can hold the maximum candies without changing the original position of selected books.

maximum candy

---

DAY2/happyNumbers.js
DAY2/permutation_step.py

“More smiling, less worrying. More compassion, less judgment. More blessed, less stressed. More love, less hate.”
― Roy T. Bennett, The Light in the Heart

LeetCode || Algorithms

---

DAY3/Repeated String Match

Given two strings A and B, find the minimum number of times A has to be repeated such that B becomes a substring of the repeated A. If B cannot be a substring of A no matter how many times it is repeated, return -1.

Repeated String Match

---

DAY5/tree_traversal

Given Preorder, Inorder, and Postorder traversals of some tree of size N. The task is to check if they are all of the same tree or not.

traversing a tree

---

DAY4/stairsPattern.py
DAY5/100Doors.js

“You could rattle the stars,” she whispered. “You could do anything, if only you dared. And deep down, you know it, too. That’s what scares you most.”

Day4 || hackerrank 

---

DAY5/100Doors.js
DAY6/evenFibonacciNumbers.js
DAY6/namesOfGod.js

Courage doesn't always roar. Sometimes courage is a quiet voice at the end of the day saying, "I will try again tomorrow."
-Mary Anne Radmacher

DAY6 || Rosetta Code 

---

DAY7/and_operator.cpp
DAY7/bit_manipulation.cpp
DAY7/or_operator.cpp
DAY7/squareofsorted_array.cpp
README.md

Use of Bitwise Operator such as AND(&&), OR( || ), XOR( ^)

Day 7 Done

---

DAY7/IsNDivisibleBy

Create a function that checks if the first argument n is divisible by all other arguments (return true if no other arguments)
Ex: IsDivisible(10,2) -> return true cause 10 is divisible by 2

Create IsNDivisibleBy - Peres

---

DAY7/MERN_CRUD_app/client/src/App.js
DAY7/MERN_CRUD_app/server/controllers/post.js
DAY7/MERN_CRUD_app/server/routes/post.js
DAY8/algorithms/noRepeatsPlease.js

"Good judgement comes from experience and experience comes from bad judgement."

DAY8 || Algorithms 

---

DAY8/SpinWords.cs

Spin words of a string if it is length is higher or equal to 5

Spin Words

---

DAY9/pairwise.js

"When you truly get over the fear of failure of perfectionism, you might be surprised how much you are capable of."

DAY9 || Algorithms 

---

DAY10/Restricted Pacman

In the game of Restricted Pacman, an infinite linear path is given. Pacman has to start at position 0 and eat as many candies as possible. In one move he can only jump a distance of either M or N.  If M and N are coprime numbers, find how many candies will be left on the board after the game is over.

Restricted Pacman

---

DAY11/LeetcodeAlgorithms/twoSum.js

“If you spend too much time thinking about a thing, you’ll never get it done. Make at least one definite move daily toward your goal.”—Bruce Lee

DAY11 || leetcode

---

DAY11/Vertical Traversal of Binary Tree
DAY6/Largest subarray with 0 sum
DAY7/Occ_of_array
DAY8/Finding middle element in a linked list
DAY9/Sort a stack
DAYLargest subarray with 0 sum

class Solution
{
public:
//Function to check whether a Binary Tree is BST or not.
bool checkbst(Node *root, int min, int max)
{
if(root==NULL)return true; 
if(root->data <= min or root->data >=max)return false; 
return checkbst(root->left,min,root->data) and checkbst(root->right,root->data,max);
}
bool isBST(Node* root) 
{
// Your code here
return  checkbst(root,INT_MIN,INT_MAX);
}
};
#driver code here

Check for BST 

---

DAY12/Smallest range in K lists

Given K sorted lists of integers, KSortedArray[] of size N each. The task is to find the smallest range that includes at least one element from each of the K lists. If more than one such range's are found, return the first such range found.

Smallest range in K lists

---

DAY12/frequency.cpp

Sorry I couldn't contribute much due to Hactoberfest and some college work .

Added count frequency question

---

DAY16/Water Connection Problem

Every house in the colony has at most one pipe going into it and at most one pipe going out of it. Tanks and taps are to be installed in a manner such that every house with one outgoing pipe but no incoming pipe gets a tank installed on its roof and every house with only an incoming pipe and no outgoing pipe gets a tap.
Given two integers n and p denoting the number of houses and the number of pipes. The connections of pipe among the houses contain three input values: ai, bi, di denoting the pipe of diameter di from house ai to house bi. Find the efficient way for the construction of the network of pipes.
The output will contain the number of pairs of tanks and taps t installed in first line and the next t lines contain three integers: house number of tank, house number of tap and the …

Water Connection Problem

---

DAY17/Edit Distance

Given two strings s and t. Find the minimum number of operations that need to be performed on str1 to convert it to str2. The possible operations are:
Insert a character at any position of the string.
Remove any character from the string.
Replace any character from the string with any other character.

Edit Distance

---

DAY20/Spiral Matrix

Given a matrix of size N x M. You have to find the Kth element which will obtain while traversing the matrix spirally starting from the top-left corner of the matrix.

Spiral Matrix

---

DAY22/Overlapping Intervals

Given a collection of Intervals, the task is to merge all of the overlapping Intervals.

Overlapping Intervals

---

DAY23/Count triplets with sum smaller than X

Given an array arr[] of distinct integers of size N and a value sum, the task is to find the count of triplets (i, j, k), having (i<j<k) with the sum of (arr[i] + arr[j] + arr[k]) smaller than the given value sum.

Count triplets with sum smaller than X

---

DAY31/Implement Queue using array

Implement a Queue using an Array. Queries in the Queue are of the following type:
(i) 1 x   (a query of this type means  pushing 'x' into the queue)
(ii) 2     (a query of this type means to pop element from queue and print the poped element)

Implement Queue using array

---

DAY41/Number of minimum picks to get 'k' pairs of socks from a drawer

A drawer contains socks of n different colours. The number of socks available of ith colour is given by a[i] where a is an array of n elements. Tony wants to take k pairs of socks out of the drawer. However, he cannot see the colour of the sock that he is picking. You have to tell what is the minimum number of socks Tony has to pick in one attempt from the drawer such that he can be absolutely sure, without seeing their colours, that he will have at least k matching pairs.

Number of minimum picks to get 'k' pairs of socks from a drawer

---

DAY42/Kth element in Matrix

Given a N x N matrix, where every row and column is sorted in non-decreasing order. Find the kth smallest element in the matrix.

Kth element in Matrix

---

DAY43/Pairs with specific difference

Given an array of integers arr[] and a number K.You can pair two numbers of the array if the difference between them is strictly less than K. The task is to find the maximum possible sum of such disjoint pairs. The Sum of P pairs is the sum of all 2P numbers of pairs.

Pairs with specific difference

---

DAY44/Circular Prime Number

A prime number is a Circular Prime Number if all of its possible rotations are itself prime numbers. Now given a number N check if it is Circular Prime or Not.

Circular Prime Number

---

DAY45/Maximum of minimum for every window size

Given an integer array. The task is to find the maximum of the minimum of every window size in the array.
Note: Window size varies from 1 to the size of the Array.

Maximum of minimum for every window size

---

DAY46/Maximize sum(arr[i]*i) of an Array

Given an array A of N integers. Your task is to write a program to find the maximum value of ∑arr[i]*i, where i = 0, 1, 2,…., n – 1.
You are allowed to rearrange the elements of the array.
Note: Since output could be large, hence module 109+7 and then print

Maximize sum(arr[i]*i) of an Array

---

DAY49/Array Subset of another array

Given two arrays: a1[0..n-1] of size n and a2[0..m-1] of size m. Task is to check whether a2[] is a subset of a1[] or not. Both the arrays can be sorted or unsorted. It may be assumed that elements in both array are distinct.

Array Subset of another array
